development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: salor_development
  username: root
  password: us3rabc123
  pool: 5
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: salor_test
  username: root
  password: us3rabc123
  pool: 5
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: salor_production
  username: root
  password: us3rabc123
  pool: 5
  host: localhost
